environment:
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false

  matrix:
    - TARGET: x86_64-pc-windows-msvc

platform:
  - x64

install:
  - set ARCH=x64

  # Install Rust
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V

  # Install OpenCV
  - echo "INSTALL OPENCV"
  - cmd: .ci\appveyor_install_OCV.sh

  # Configure OpenCV
  - echo "CONFIGURE OPENCV"
  - set APP_PATH=%CD%
  - CD Install\opencv
  - echo "SET OPENCV_DIR"
  - set OPENCV_DIR=%CD%
  - cd %APP_PATH%
  - set OPENCV_LIB=%OPENCV_DIR%\%ARCH%\vc15\lib
  - set PATH=%OPENCV_DIR%\%ARCH%\vc15\bin;%PATH%

build: false

test_script:
  - cargo build --no-default-features
  - cargo test --no-default-features
  # - cargo build --features gpu
  # - cargo test --features gpu
