image: Visual Studio 2017
max_jobs: 4
environment:
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false

  matrix:
    - TARGET: x86_64-pc-windows-msvc

platform:
  - x64

install:
  - set ARCH=x64
  
  # Install CUDA
  - ps: appveyor DownloadFile https://developer.nvidia.com/compute/cuda/8.0/prod/local_installers/cuda_8.0.44_windows-exe -FileName cuda_8.0.44_windows.exe
  - ps: Start-Process -FilePath "cuda_8.0.44_windows.exe" -ArgumentList "-s compiler_8.0" -Wait
  - ps: .ci\appveyor_install_CUDA.ps1
  - cmd: set PATH=%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin;%ProgramFiles%\NVIDIA GPU Computing Toolkit\CUDA\v8.0\libnvvp;%PATH%
  - cmd: nvcc -V

build: false

test_script:
  # - cargo build --no-default-features
  # - cargo test --no-default-features
  # - cargo build --features gpu
  # - cargo test --features gpu
