image: Previous Visual Studio 2017
environment:
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false

  matrix:
    - TARGET: x86_64-pc-windows-msvc

platform:
  - x64

install:  
  # Install CUDA
  - ps: appveyor DownloadFile https://developer.nvidia.com/compute/cuda/9.1/Prod/local_installers/cuda_9.1.85_win10 -FileName cuda.exe
  - ps: .\.ci\appveyor_install_CUDA.ps1 -FileName cuda.exe
  
  # Install OpenCV
  - ps: .\.ci\appveyor_build_OCV.ps1

  # Install Rust
  - cmd: set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -V
  - cargo -V
  
build: false
cache:
  - install -> .ci\appveyor_build_OCV.ps1, .ci\appveyor_build_CUDA.ps1
test_script:
  - cargo build --no-default-features
  - cargo test --no-default-features
  # - cargo build --features gpu
  # - cargo test --features gpu
