image: Visual Studio 2017
environment:
  RUSTUP_USE_REQWEST: 1
  CARGO_HTTP_CHECK_REVOKE: false

  matrix:
    - TARGET: x86_64-pc-windows-msvc

platform:
  - x64

install:
  - set ARCH=x64
  
  # Install CUDA
  - cmd: .ci\appveyor_install_CUDA.cmd

build: false

test_script:
  # - cargo build --no-default-features
  # - cargo test --no-default-features
  # - cargo build --features gpu
  # - cargo test --features gpu
